CREATE SCHEMA rooms;

REVOKE CREATE ON SCHEMA rooms FROM jgame_backend;

GRANT USAGE ON SCHEMA rooms TO jgame_backend;
ALTER DEFAULT PRIVILEGES IN SCHEMA rooms
  GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLES TO jgame_backend;
ALTER DEFAULT PRIVILEGES IN SCHEMA rooms
  GRANT USAGE, SELECT ON SEQUENCES TO jgame_backend;
