ALTER DEFAULT PRIVILEGES
  IN SCHEMA public
  REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES
  IN SCHEMA public
  REVOKE ALL ON TABLES FROM jgame_backend;

REVOKE CREATE ON SCHEMA users FROM jgame_backend;
REVOKE CREATE ON SCHEMA packs FROM jgame_backend;
