DO $$
BEGIN
  ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    REVOKE ALL ON TABLES FROM PUBLIC;
  ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    REVOKE ALL ON TABLES FROM :USER;
  ALTER DEFAULT PRIVILEGES
    IN SCHEMA users
    REVOKE CREATE ON SCHEMA users FROM :USER;
  ALTER DEFAULT PRIVILEGES
    IN SCHEMA users
    REVOKE CREATE ON SCHEMA packs FROM :USER;
END
$$;
