DO $$
BEGIN
  GRANT USAGE ON SCHEMA users TO :USER;
  GRANT USAGE ON SCHEMA packs TO :USER;

  ALTER DEFAULT PRIVILEGES IN SCHEMA users
    GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLES TO :USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA users
    GRANT USAGE, SELECT ON SEQUENCES TO :USER;

  ALTER DEFAULT PRIVILEGES IN SCHEMA packs 
    GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLES TO :USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA packs
    GRANT USAGE, SELECT ON SEQUENCES TO :USER;
END
$$;
